name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Build Server
      run: |
        mkdir ./target
        make server
    - name: Build Client
      run: |
        make client